### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by dashuchichichixigua** [sometimesstudy/two-stage-robust-optimization#1]
您好老师，
很高兴在这里看到您分享的代码，很遗憾我看到您把矩阵数据给删除了，现在我很想自己尝试运行这个代码，想把这篇文章的推导搞懂，不知道您这边方便分析一下数据吗，谢谢老师。
祝老师身体健康，工作顺利（邮箱，kangkliyan00@163.com）

**Comment by sometimesstudy** [comment]
已补充数据

**Comment by xiongxs2** [comment]
您好，老师，看您之前有卫星调度问题的代码，我最近在做这方面的研究，因为复现不太顺利，非常想要这方便的代码，不知道老师方便分享一下代码不呢。
祝老师工作顺利，事事顺心！我的邮箱（xiong05340@my.swjtu.edu.cn）
